# Generated by Django 5.0.6 on 2024-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('milk_production', models.FloatField(help_text='Milk production in liters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('health', models.TextField()),
            ],
        ),
    ]
