# Generated by Django 5.0.6 on 2024-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='milk_production',
            field=models.FloatField(help_text='Milk production in litres'),
        ),
    ]
