# Generated by Django 5.0.3 on 2024-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0004_remove_cow_milk_production_cow_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
