# Generated by Django 5.0.3 on 2024-06-13 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0003_milkrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='milk_production',
        ),
        migrations.AddField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of birth'),
        ),
    ]
